/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiSwarmRouteImport } from './routes/api/swarm'
import { Route as ApiX402ChatRouteImport } from './routes/api/x402/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSwarmRoute = ApiSwarmRouteImport.update({
  id: '/api/swarm',
  path: '/api/swarm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiX402ChatRoute = ApiX402ChatRouteImport.update({
  id: '/api/x402/chat',
  path: '/api/x402/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/swarm': typeof ApiSwarmRoute
  '/api/x402/chat': typeof ApiX402ChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/swarm': typeof ApiSwarmRoute
  '/api/x402/chat': typeof ApiX402ChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/swarm': typeof ApiSwarmRoute
  '/api/x402/chat': typeof ApiX402ChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/chat' | '/api/swarm' | '/api/x402/chat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/chat' | '/api/swarm' | '/api/x402/chat'
  id: '__root__' | '/' | '/api/chat' | '/api/swarm' | '/api/x402/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiSwarmRoute: typeof ApiSwarmRoute
  ApiX402ChatRoute: typeof ApiX402ChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/swarm': {
      id: '/api/swarm'
      path: '/api/swarm'
      fullPath: '/api/swarm'
      preLoaderRoute: typeof ApiSwarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/x402/chat': {
      id: '/api/x402/chat'
      path: '/api/x402/chat'
      fullPath: '/api/x402/chat'
      preLoaderRoute: typeof ApiX402ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiSwarmRoute: ApiSwarmRoute,
  ApiX402ChatRoute: ApiX402ChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
